#ifndef ERR_CODE_H
#define ERR_CODE_H

#define ADAS_OK 0

//Coordinate Transfer module
#define COORDTRANSFER_ERR_CAMERA_INVALID_CONFIG_FILE 1201
#define COORDTRANSFER_ERR_CAMERA_INVALID_CONFIG_PARAM 1202
#define COORDTRANSFER_ERR_CAMERA_INVALID_CALIB_FILE 1203
#define COORDTRANSFER_ERR_CAMERA_INVALID_CALIB_PARAM 1204
#define COORDTRANSFER_ERR_RADAR_INVALID_CONFIG_FILE 1205
#define COORDTRANSFER_ERR_RADAR_INVALID_CONFIG_PARAM 1206

#define COORDTRANSFER_ERR_NEG_DISTANCE 1207
#define COORDTRANSFER_ERR_OUT_IMAGE_RANGE 1208

#define ERR_SENSOR_INIT_FAILURE 1301
#define ERR_SENSOR_OPEN_FAILURE 1302
#define ERR_CAMERA_INIT_FAILURE 1303
#define ERR_SYSTEM_INIT_FAILURE 1304
#define ERR_IMU_PROC_INIT_FAILURE 1305
#define ERR_INI_PARSER_INIT_FAILURE 1306
#define ERR_CAMERA_CALIB_CONFIG_FAILURE 1307
#define ERR_CONTI_408_GRABBER_INIT_FAILURE 1307

//EnhancedMath
#define ENHANCEDMATH_ERR_POINTS_INSUFFICIENT 1900
#define ENHANCEDMATH_ERR_LARGE_REGRESSION_ERR 1901

//-----Data source and proc-----
//API


//IMUProc
#define IMUPROC_ERR_INVALID_CONFIG_FILE 2501
#define IMUPROC_ERR_UPDATE_TILT_PAN_ROLL_6_AXIS_FAILURE 2502
#define IMUPROC_ERR_INVALID_TIMESTAMP 2503
#define IMUPROC_ERR_INVALID_CONFIG_VALUE 2504

#endif	//ERR_CODE_H
